name: documentation-builder
version: '1.5.1'
summary: Build HTML documentation from markdown
description: |
  A tool to build repositories of markdown files of documentation into HTML pages

grade: stable
confinement: classic

parts:
  repo:
    plugin: python
    source: .
  copy:
    plugin: dump
    source: .
  git:
    plugin: autotools
    source: https://github.com/git/git/archive/v2.10.2.tar.gz

apps:
  documentation-builder:
    plugs:
        - home
    command: documentation-builder
